import React from 'react'
import Form from './Form'

describe('<Form />', () => {
  it('renders', () => {
    cy.viewport(900, 500)
    // see: https://on.cypress.io/mounting-react
    cy.mount(<Form />)
  })

  it('won\'t submit if the form is not filled out', () => {
    cy.viewport(900, 500)
    cy.mount(<Form />)
    cy.get('.mantine-Stack-root > .mantine-8od8ev > .mantine-UnstyledButton-root')
      .should('exist')
      .should('be.disabled')
      
  })

  it('won\'t submit if the second stage is not filled out', () => {
    cy.viewport(900, 500)
    cy.mount(<Form />)
    cy.get('#mantine-r2')
      .should('exist')
      .focus()
      .type('https://ourworldindata.org/uploads/2018/11/Annual-World-Population-since-10-thousand-BCE-for-OWID-800x498.png')
      cy.get('.mantine-Stack-root > .mantine-8od8ev > .mantine-UnstyledButton-root')
      .should('exist')
      .should('not.be.disabled')
      .click()
    cy.get('[type="submit"]')
      .should('exist')
      .should('be.disabled')
  })

  it('will submit if the form is filled out', () => {
    cy.viewport(900, 500)
    cy.mount(<Form />)
    cy.get('#mantine-r4')
      .should('exist')
      .focus()
      .type('https://ourworldindata.org/uploads/2018/11/Annual-World-Population-since-10-thousand-BCE-for-OWID-800x498.png')
      cy.get('.mantine-Stack-root > .mantine-8od8ev > .mantine-UnstyledButton-root')
      .should('exist')
      .should('not.be.disabled')
      .click()
    cy.get('#mantine-r5')
      .should('exist')
      .focus()
      .type('Sample Project')
    cy.get('[type="submit"]')
      .should('exist')
      .should('not.be.disabled')
  })

  it('saves form data when going back', () => {
    cy.viewport(900, 500)
    cy.mount(<Form />)
    cy.get('#mantine-r6')
      .should('exist')
      .focus()
      .type('https://ourworldindata.org/uploads/2018/11/Annual-World-Population-since-10-thousand-BCE-for-OWID-800x498.png')
      cy.get('.mantine-Stack-root > .mantine-8od8ev > .mantine-UnstyledButton-root')
      .should('exist')
      .should('not.be.disabled')
      .click()
    cy.get('#mantine-r7')
      .should('exist')
      .focus()
      .type('Sample Project')
    cy.get('.mantine-8od8ev > [type="button"]')
      .should('exist')
      .click()
    cy.get('#mantine-r8')
      .should('exist')
      .should('have.value', 'https://ourworldindata.org/uploads/2018/11/Annual-World-Population-since-10-thousand-BCE-for-OWID-800x498.png')
    cy.get('.mantine-Stack-root > .mantine-8od8ev > .mantine-UnstyledButton-root')
      .should('exist')
      .should('not.be.disabled')
      .click()
    cy.get('#mantine-r9')
      .should('exist')
      .should('have.value', 'Sample Project')
  })

  it('won\'t submit if image URL is not an accepted format', () => {
    cy.viewport(900, 500)
    cy.mount(<Form />)
    cy.get('#mantine-ra')
      .should('exist')
      .focus()
      .type('not a link')
    cy.get('.mantine-Stack-root > .mantine-8od8ev > .mantine-UnstyledButton-root')
      .should('exist')
      .should('not.be.disabled')
      .click()
    cy.get('.mantine-InputWrapper-error')
      .should('exist')
  })
})