name: Generate Static Build Files
run-name: ${{ github.actor }} is generating static build files
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn export
